import { cache } from "react";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { LandingNav } from "@/components/landing/nav";
import { Footer } from "@/components/landing/footer";
import { BriefingCard, type Briefing } from "@/components/app/briefing-card";
import { getById } from "@/lib/repos/research-sessions";

// Dedupe the DB read between generateMetadata and the page render.
const load = cache(async (id: string) => getById(id));

function toBriefing(row: NonNullable<Awaited<ReturnType<typeof getById>>>): Briefing {
  return {
    id: row.id,
    topic: row.topic,
    briefing: row.briefing.briefing,
    confidence: row.briefing.confidence,
    sources: row.briefing.sources,
    partial: row.briefing.partial,
    createdAt: new Date(row.createdAt).toISOString(),
    paymentTx: row.paymentTx,
    topicType: row.briefing.topicType ?? null,
    freshness: row.briefing.freshness ?? [],
  };
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;
  const row = await load(id);
  if (!row) return { title: "briefing not found · pyxis" };

  const title = `${row.topic} · pyxis briefing`;
  const description = row.briefing.briefing
    .replace(/[#*`>_\-\[\]()]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 155);

  return {
    title,
    description,
    openGraph: { title, description, type: "article", url: `https://usepyxis.com/b/${id}` },
    twitter: { card: "summary_large_image", title, description },
  };
}

export default async function PublicBriefingPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const row = await load(id);
  if (!row) notFound();

  const b = toBriefing(row);

  return (
    <main className="relative term-grid-bg min-h-screen">
      <LandingNav />

      <section className="max-w-[920px] mx-auto px-6 lg:px-8 pt-10 lg:pt-14 pb-16">
        <div className="mb-6 flex items-center gap-3">
          <span className="term-section-tag">// shared briefing</span>
          <span className="font-mono text-[10px] uppercase tracking-[0.18em] text-[var(--muted)]">
            generated by pyxis · read-only
          </span>
        </div>

        <BriefingCard b={b} active />

        {/* Conversion CTA — public viewers land here from a shared link */}
        <div className="mt-8 term-block flex flex-wrap items-center justify-between gap-4">
          <div className="font-mono text-[13px] text-[var(--muted)] leading-[1.6]">
            <span className="text-[var(--foreground)]">run your own research</span> — five
            agents, 13 live sources, every number stamped. free during beta.
          </div>
          <Link href="/research" className="term-cta shrink-0">
            open pyxis
            <span className="text-[16px] leading-none translate-y-[-1px]">›</span>
          </Link>
        </div>
      </section>

      <Footer />
    </main>
  );
}
